export const globalPhonetics = {
  "AI": "ey ay",
  "IT": "ay ti",
  "CEO": "si i o",
  "VIP": "vi ay pi",
  "API": "ei pi ay",
  "WA": "we a",
  "KTP": "ka te pe",
  "KK": "ka ka",
  "BPJS": "be pe je es",
  "WIB": "we i be",
  "WITA": "we i te a",
  "WIT": "we i te",
  "FYP": "ef ye pe",
  "UU": "u u",
  "UUD": "u u de",
  "NKRI": "en ka er i",
  "IG": "i ge",
  "FB": "ef be",
  "TTS": "te te es",
  "PNS": "pe en es",
  "BUMN": "be u em en",
  "SIM": "es i em",
  "STNK": "es te en ka",
  "PBB": "pe be be",
  "LRT": "el er te",
  "MRT": "em er te",
  "KRL": "ka er el",
  "BBM": "be be em",
  "QRIS": "kris",
  "OJK": "o je ka",
  "PPN": "pe pe en",
  "PPh": "pe pe ha",
  "IKN": "i ka en",
  "UMKM": "u em ka em",
  "SME": "es em i",
  "UI": "u i",
  "ITB": "i te be",
  "UGM": "u ge em",
  "UNPAD": "un pad",
  "IPB": "i pe be",
  "GoJek": "go jek",
  "Grab": "grep",
  "Tokopedia": "tokopedia",
  "Shopee": "shopi",
  "Bukalapak": "bukalapak",
  "Lazada": "lazada",
  "Blibli": "bli bli",
  "Tiktok": "tik tok",
  "Instagram": "instagram",
  "Facebook": "fesbuk",
  "Twitter": "twiter",
  "Youtube": "yutup",
  "WhatsApp": "wats ap",
  "Telegram": "telegram",
  "Google": "gugel",
  "Microsoft": "maikrosof",
  "Apple": "epel",
  "Samsung": "samsung",
  "Website": "websait",
  "Online": "onlain",
  "Offline": "oflain",
  "Download": "daunlod",
  "Upload": "aplod",
  "Update": "apdet",
  "Login": "login",
  "Logout": "log-out",
  "Email": "imel",
  "Chat": "cet",
  "Content": "konten",
  "Creator": "kri-ey-tor",
  "Shorts": "sorts",
  "Reels": "rils",
  "Podcast": "podkes",
  "Digital": "dijital",
  "Modern": "modern",
  "Premium": "primium",
  "Standard": "standar",
  "Support": "saport",
  "Help": "help",
  "Contact": "kontak",
  "About": "ebaut",
  "Home": "hom",
  "Share": "ser",
  "Like": "laik",
  "Subscribe": "sabskraib",
  "Follow": "folo",
  "Comment": "komen",
  "Notification": "notifikasi",
  "Setting": "seting",
  "Profile": "profil",
  "Account": "akaun",
  "Password": "pasword",
  "Username": "yusernem",
  "Admin": "admin",
  "User": "yuser",
  "Member": "member",
  "Free": "fri",
  "Trial": "trayel",
  "Package": "pekej",
  "Plan": "plen",
  "Price": "prais",
  "Payment": "pey-men",
  "Transfer": "transfer",
  "Bank": "beng",
  "Card": "kard",
  "Success": "sukses",
  "Failed": "feild",
  "Error": "eror",
  "Warning": "worning",
  "Danger": "denjer",
  "Safe": "sef",
  "Secure": "sekyur",
  "Private": "praivet",
  "Public": "pablik",
  "Open": "open",
  "Close": "klos",
  "Start": "start",
  "Finish": "finis",
  "Stop": "stop",
  "Cancel": "kensel",
  "Save": "sev",
  "Edit": "edit",
  "Delete": "dilit",
  "Remove": "rimuv",
  "Add": "ed",
  "Search": "serch",
  "Filter": "filter",
  "Sort": "sort",
  "View": "vyu",
  "List": "lis",
  "Grid": "grid",
  "Card": "kard",
  "Table": "tebel",
  "Menu": "menyu",
  "Nav": "nef",
  "Header": "heder",
  "Footer": "futer",
  "Body": "badi",
  "Text": "teks",
  "Voice": "vois",
  "Audio": "odyo",
  "Video": "vidyo",
  "Image": "imej",
  "File": "fail",
  "Folder": "folder",
  "App": "ep",
  "Software": "sofwer",
  "Hardware": "hardwer",
  "System": "sistem",
  "Data": "data",
  "Database": "detabes",
  "Server": "server",
  "Cloud": "klaud",
  "Network": "netwurk",
  "Internet": "internet",
  "Mobile": "mobail",
  "Desktop": "destop",
  "Laptop": "leptop",
  "PC": "pi si",
  "Camera": "kemera",
  "Photo": "foto",
  "Video": "vidyo",
  "Music": "myusik",
  "Game": "gem",
  "Play": "ple",
  "Pause": "pos",
  "Stop": "stop",
  "Next": "neks",
  "Prev": "prev",
  "Back": "bek",
  "Forward": "forward",
  "Up": "ap",
  "Down": "daun",
  "Left": "left",
  "Right": "rait",
  "Center": "senter",
  "Top": "top",
  "Bottom": "botom",
  "Middle": "midel",
  "Space": "spes",
  "Enter": "enter",
  "Shift": "sif",
  "Ctrl": "kontrol",
  "Alt": "alt",
  "Tab": "teb",
  "Esc": "eskep",
  "Delete": "dilit",
  "Backspace": "bekspes",
  "Insert": "insert",
  "Home": "hom",
  "End": "end",
  "Page": "pej",
  "Print": "print",
  "Screen": "skrin",
  "Keyboard": "kibord",
  "Mouse": "maus",
  "Monitor": "monitor",
  "Speaker": "spiker",
  "Mic": "maik",
  "Headphone": "hedfon",
  "Headset": "hedset",
  "Battery": "batere",
  "Charger": "carjer",
  "Cable": "kabel",
  "USB": "yu es bi",
  "Bluetooth": "blutut",
  "WiFi": "way-fay",
  "Signal": "sinyal",
  "Speed": "spid",
  "Level": "level",
  "Mode": "mod",
  "Status": "status",
  "Info": "info",
  "News": "nyus",
  "Event": "efen",
  "Date": "det",
  "Time": "taim",
  "Day": "de",
  "Week": "wik",
  "Month": "man",
  "Year": "yir",
  "Second": "sekon",
  "Minute": "menit",
  "Hour": "jam",
  "Clock": "klok",
  "Watch": "woc",
  "Box": "boks",
  "Card": "kartu",
  "Badge": "be-je",
  "Point": "poin",
  "Rank": "reng",
  "Team": "tim",
  "Squad": "sku-ad",
  "Club": "klab",
  "Boss": "bos",
  "King": "king",
  "Queen": "kuin",
  "Hero": "hiro",
  "Star": "star",
  "Winner": "winer",
  "Looser": "luser",
  "Fight": "fait",
  "Win": "win",
  "Lost": "lost",
  "Draw": "dro",
  "Match": "mec",
  "Round": "raun",
  "Stage": "stej",
  "Quest": "kwes",
  "Mission": "misi",
  "Skill": "skil",
  "Exp": "e ek es pe",
  "Hp": "ha pe",
  "Mp": "em pe",
  "Gold": "gold",
  "Diamond": "day-men",
  "Item": "aitem",
  "Skin": "skin",
  "Pet": "pet",
  "Map": "mep",
  "Shop": "sop",
  "Gacha": "gaca",
  "Lucky": "laki",
  "Spin": "spin",
  "Claim": "klem",
  "Reedem": "ridim",
  "Promo": "promo",
  "Sale": "sel",
  "Voucher": "vaucer",
  "Coupon": "kupon",
  "Discount": "diskon",
  "Cashback": "kes-bek",
  "Coin": "koin",
  "Token": "token",
  "Credit": "kredit",
  "Points": "poin",
  "Rating": "re-ting",
  "Review": "rivyu",
  "Shield": "sild",
  "Sword": "swod",
  "Gun": "gan",
  "Armor": "armor",
  "Magic": "mejik",
  "Mana": "mana",
  "Power": "power",
  "Health": "hel",
  "Life": "laif",
  "Death": "det",
  "Monster": "monster",
  "Enemy": "enemi",
  "Friend": "fren",
  "Guild": "gild",
  "Alli": "ali",
  "Clan": "klen",
  "War": "wor",
  "Battle": "betel",
  "Arena": "arena",
  "Lobby": "lobi",
  "Room": "rum",
  "Ping": "ping",
  "Lag": "leg",
  "Banned": "ben",
  "Report": "report",
  "Hack": "hek",
  "Cheat": "cit",
  "Bug": "bag",
  "Fix": "fiks",
  "Drop": "drop",
  "Frame": "frem",
  "Fps": "ef pi es",
  "Hd": "ha de",
  "Uhd": "yu ha de",
  "4k": "for ke",
  "Bitrate": "bit-ret",
  "Render": "render",
  "Export": "eksport",
  "Import": "import",
  "Layer": "leyer",
  "Effect": "efek",
  "Keyframe": "kifrem",
  "Timeline": "taimlain",
  "Split": "split",
  "Join": "join",
  "Cut": "kat",
  "Copy": "kopi",
  "Paste": "pest",
  "Select": "selek",
  "Clear": "klir",
  "Reset": "riset",
  "Undo": "andu",
  "Redo": "ridu",
  "Zoom": "zum",
  "Fit": "fit",
  "Full": "ful",
  "Mini": "mini",
  "Large": "lar-je",
  "Small": "smol",
  "Normal": "normal",
  "Auto": "oto",
  "Manual": "man-u-el",
  "Custom": "kostum",
  "Default": "difolt",
  "Ready": "redi",
  "Go": "go",
  "Wait": "wet",
  "Loading": "loding",
  "Processing": "prosesing",
  "Done": "dan",
  "Exit": "eksit",
  "Skip": "skip",
  "Record": "rekord",
  "Stream": "strim",
  "Live": "laiv",
  "Vlog": "vlog",
  "Post": "pos",
  "Feed": "fid",
  "Highlight": "hailait",
  "Explore": "eksplor",
  "Message": "mesej",
  "Direct": "dairek",
  "Group": "grup",
  "Call": "kol",
  "Note": "not",
  "Poll": "pol",
  "Location": "lokesyon",
  "Document": "dokumen",
  "Request": "rikwes",
  "Privacy": "prai-vasi",
  "Security": "sekyuriti",
  "Storage": "store-je",
  "Cache": "kes",
  "Version": "versiyon",
  "Feedback": "fidbek",
  "Invite": "infait",
  "Scan": "sken",
  "Pay": "pay",
  "Bill": "bil",
  "Topup": "top-ap",
  "Withdraw": "wit-dro",
  "Reward": "ri-wod",
  "Subscription": "sabskripsyon",
  "Renew": "renyu",
  "Expired": "ekspairet",
  "Active": "aktif",
  "Pending": "pending",
  "Refund": "rifand",
  "Checkout": "cek-aut",
  "Wishlist": "wislis",
  "Tax": "teks",
  "Subtotal": "sabtotal",
  "Shipping": "siping",
  "Delivery": "deliveri",
  "Tracking": "treking",
  "Weight": "weit",
  "Gram": "gram",
  "Meter": "meter",
  "Inch": "inci",
  "Liter": "liter",
  "Qty": "ki ti way",
  "Piece": "pis",
  "Product": "produk",
  "Brand": "bren",
  "Category": "kategori",
  "Type": "taip",
  "Color": "kolor",
  "Model": "model",
  "Series": "sirius",
  "Made": "med",
  "Original": "orijinal",
  "Official": "ofisiyel",
  "Authentic": "otentik",
  "Refurbished": "rifurbis",
  "Vintage": "vintij",
  "Retro": "retro",
  "Classic": "klasik",
  "Futuristic": "fyuturistik",
  "Smart": "smart",
  "Fast": "fas",
  "Slow": "slo",
  "Easy": "isi",
  "Hard": "hard",
  "Simple": "simpel",
  "Complex": "kompleks",
  "Normal": "normal",
  "Auto": "oto",
  "Thin": "tin",
  "Thick": "tik",
  "Heavy": "hevi",
  "Light": "lait",
  "Dark": "dark",
  "Bright": "brait",
  "Red": "red",
  "Blue": "blu",
  "Green": "grin",
  "Yellow": "yelo",
  "Black": "blek",
  "White": "wait",
  "Grey": "gre",
  "Shiny": "saini",
  "Matte": "met",
  "Soft": "sof",
  "Smooth": "smut",
  "Rough": "raf",
  "Clean": "klin",
  "Dirty": "dirti",
  "Shinerva": "shi ner va",
  "RUNGU": "ru ngu",
  "ElevenLabs": "ilefen lebs"
};
