/**
 * SHINERVA - Robust Email Service with SMTP-to-Gmail Fallback
 * ===========================================================
 * Primary: Custom domain SMTP (admin@shinerva.id / support@shinerva.id)
 * Fallback: Gmail (hello.shinerva@gmail.com)
 *
 * Handles: Magic Link generation + delivery, Email Verification,
 * Password Reset, and any transactional emails.
 *
 * Token integrity: All tokens are generated by Firebase Admin SDK on the
 * server — email transport only handles delivery. Token cannot be tampered
 * with by the transport layer.
 */

import nodemailer from 'nodemailer';
import admin from 'firebase-admin';

// ─── Transporter Initialization ───────────────────────────────────────────────
const createPrimaryTransport = () => {
  const host = process.env.EMAIL_HOST;
  const port = Number(process.env.EMAIL_PORT) || 587;
  const secure = process.env.EMAIL_SECURE === 'true';

  if (!host || !process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
    return null;
  }

  return nodemailer.createTransport({
    host,
    port,
    secure, // true = 465, false = 587/STARTTLS
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
    // Connection pool settings
    pool: true,
    maxConnections: 5,
    maxMessages: 100,
    // Timeout settings
    connectionTimeout: 15000,  // 15s to establish connection
    greetingTimeout: 15000,
    socketTimeout: 30000,      // 30s per operation
  });
};

const createFallbackTransport = () => {
  if (!process.env.FALLBACK_EMAIL || !process.env.FALLBACK_EMAIL_PASSWORD) {
    return null;
  }
  return nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: process.env.FALLBACK_EMAIL,
      pass: process.env.FALLBACK_EMAIL_PASSWORD,
    },
    pool: true,
    maxConnections: 3,
    maxMessages: 50,
    connectionTimeout: 15000,
    socketTimeout: 30000,
  });
};

let primaryTransport = null;
let fallbackTransport = null;
let firebaseAdminAuth = null;

function initServices() {
  primaryTransport = createPrimaryTransport();
  fallbackTransport = createFallbackTransport();

  // Get Firebase Admin auth instance
  try {
    const firebaseApp = admin.apps.length > 0 ? admin.apps[0] : null;
    if (firebaseApp) {
      firebaseAdminAuth = admin.auth(firebaseApp);
    }
  } catch (_) {
    console.warn('[Email] Firebase Admin not available — token generation disabled');
  }
}

initServices();


/**
 * Verifies SMTP connection health before attempting send.
 * Catches connection errors early to switch transporter proactively.
 */
async function probeTransport(transport, label) {
  try {
    await new Promise((resolve, reject) => {
      transport.verify((error, success) => {
        if (error) reject(error);
        else resolve(success);
      });
    });
    return true;
  } catch (err) {
    console.warn(`[Email] ${label} probe failed: ${err.message}`);
    return false;
  }
}

// ─── Magic Link Token Generation ─────────────────────────────────────────────

/**
 * Generates a Firebase magic link token server-side using Firebase Admin SDK.
 * This token is cryptographically signed by Firebase — the email transport
 * only delivers the URL. Token integrity is guaranteed by Firebase.
 *
 * @param {string} email - Recipient email
 * @param {string} continueUrl - URL to redirect after click
 * @returns {Promise<string>} - Complete magic link URL
 */
export async function generateMagicLinkToken(email, continueUrl) {
  if (!firebaseAdminAuth) {
    throw new Error('Firebase Admin Auth not initialized');
  }

  const actionCodeSettings = {
    url: continueUrl || process.env.EMAIL_CONTINUE_URL || process.env.APP_URL || 'https://shinerva.id',
    handleCodeInApp: true,
  };

  try {
    const link = await firebaseAdminAuth.generateSignInWithEmailLink(email, actionCodeSettings);
    console.log(`[Email] Magic link generated for ${email}`);
    return link;
  } catch (err) {
    console.error(`[Email] Magic link generation failed for ${email}:`, err.message);
    throw new Error(`Gagal membuat link masuk: ${err.message}`);
  }
}

// ─── Email Templates ─────────────────────────────────────────────────────────

function buildMagicLinkEmail(link, email) {
  return {
    subject: 'Masuk ke Shinerva — Klik Link di Bawah Ini',
    html: `
<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Masuk Shinerva</title>
</head>
<body style="margin:0;padding:0;background:#1a1a1a;font-family:Inter,Arial,sans-serif;color:#FDFBF7;">
  <div style="max-width:480px;margin:0 auto;padding:40px 20px;text-align:center;">
    <img src="${process.env.APP_URL || 'https://shinerva.id'}/shinerva-icon.png" alt="Shinerva" style="width:64px;height:64px;margin-bottom:24px;" />
    <h1 style="color:#e2725b;font-size:24px;font-weight:900;margin:0 0 8px;">Masuk ke Shinerva</h1>
    <p style="color:#8a8a8a;font-size:14px;margin:0 0 32px;">Klik tombol di bawah untuk masuk ke akun Anda.</p>
    <a href="${link}"
       style="display:inline-block;background:#e2725b;color:#FDFBF7;text-decoration:none;font-weight:700;font-size:16px;
              padding:14px 32px;border-radius:9999px;margin-bottom:24px;">
      Masuk Sekarang
    </a>
    <p style="color:#555;font-size:12px;margin:0 0 8px;">
      Link ini berlaku selama 1 jam dan hanya untuk <strong>${email}</strong>.
    </p>
    <p style="color:#444;font-size:11px;margin:0;">
      Jika Anda tidak meminta link ini, abaikan email ini.<br/>
      Dibuat oleh <strong>Shinerva AI Voice</strong>.
    </p>
  </div>
</body>
</html>`,
  };
}

function buildVerificationEmail(link, email) {
  return {
    subject: 'Verifikasi Email Anda — Shinerva',
    html: `
<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Verifikasi Email</title>
</head>
<body style="margin:0;padding:0;background:#1a1a1a;font-family:Inter,Arial,sans-serif;color:#FDFBF7;">
  <div style="max-width:480px;margin:0 auto;padding:40px 20px;text-align:center;">
    <img src="${process.env.APP_URL || 'https://shinerva.id'}/shinerva-icon.png" alt="Shinerva" style="width:64px;height:64px;margin-bottom:24px;" />
    <h1 style="color:#e2725b;font-size:24px;font-weight:900;margin:0 0 8px;">Verifikasi Email</h1>
    <p style="color:#8a8a8a;font-size:14px;margin:0 0 32px;">
      Klik tombol di bawah untuk memverifikasi email <strong>${email}</strong>.
    </p>
    <a href="${link}"
       style="display:inline-block;background:#e2725b;color:#FDFBF7;text-decoration:none;font-weight:700;font-size:16px;
              padding:14px 32px;border-radius:9999px;margin-bottom:24px;">
      Verifikasi Sekarang
    </a>
    <p style="color:#555;font-size:12px;margin:0 0 8px;">
      Link verifikasi berlaku selama 1 jam.
    </p>
    <p style="color:#444;font-size:11px;margin:0;">
      Jika Anda tidak membuat akun di Shinerva, abaikan email ini.<br/>
      Dibuat oleh <strong>Shinerva AI Voice</strong>.
    </p>
  </div>
</body>
</html>`,
  };
}

function buildPasswordResetEmail(link) {
  return {
    subject: 'Reset Password — Shinerva',
    html: `
<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Reset Password</title>
</head>
<body style="margin:0;padding:0;background:#1a1a1a;font-family:Inter,Arial,sans-serif;color:#FDFBF7;">
  <div style="max-width:480px;margin:0 auto;padding:40px 20px;text-align:center;">
    <img src="${process.env.APP_URL || 'https://shinerva.id'}/shinerva-icon.png" alt="Shinerva" style="width:64px;height:64px;margin-bottom:24px;" />
    <h1 style="color:#e2725b;font-size:24px;font-weight:900;margin:0 0 8px;">Reset Password</h1>
    <p style="color:#8a8a8a;font-size:14px;margin:0 0 32px;">Klik tombol di bawah untuk mereset password akun Anda.</p>
    <a href="${link}"
       style="display:inline-block;background:#e2725b;color:#FDFBF7;text-decoration:none;font-weight:700;font-size:16px;
              padding:14px 32px;border-radius:9999px;margin-bottom:24px;">
      Reset Password
    </a>
    <p style="color:#555;font-size:12px;margin:0;">Link ini berlaku selama 1 jam. Jika Anda tidak meminta reset, abaikan email ini.</p>
  </div>
</body>
</html>`,
  };
}

// ─── Core Send Function ─────────────────────────────────────────────────────

/**
 * Sends an email with full primary→fallback cascade.
 *
 * Cascade logic:
 *  1. Try to send via primary custom domain SMTP (admin@shinerva.id / support@shinerva.id)
 *  2. On primary error (network, auth, SMTP rejection): immediately catch and fall back to Gmail
 *  3. On Gmail error: throw with combined error info
 *
 * The email content (from/subject/html) is built BEFORE sending, so the
 * same template is used regardless of which transport delivers it.
 * The magic link token is pre-generated by Firebase Admin SDK — the
 * transport only carries the pre-signed URL.
 *
 * @param {string} to - Recipient email
 * @param {string} subject - Email subject
 * @param {string} html - Email HTML body
 * @returns {{ success: true, transport: string }}
 */
export async function sendEmail({ to, subject, html }) {

  // Determine from address
  const primaryUser = process.env.EMAIL_USER || '';
  const allowedPrimary = ['admin@shinerva.id', 'support@shinerva.id'];
  const fromAddress = process.env.EMAIL_FROM
    || (allowedPrimary.includes(primaryUser) ? primaryUser : 'support@shinerva.id');

  const mailOptions = { from: fromAddress, to, subject, html };

  // ── Try Primary SMTP ──────────────────────────────────────────────────────
  if (primaryTransport) {
    try {
      await primaryTransport.sendMail(mailOptions);
      console.log(`[Email] ✓ Sent via primary SMTP (${fromAddress}) → ${to}`);
      return { success: true, transport: 'primary SMTP', from: fromAddress };
    } catch (primaryErr) {
      console.warn(`[Email] Primary SMTP failed for ${to}: ${primaryErr.message} (code: ${primaryErr.code})`);
      
      const isAuthErr = primaryErr.code === 'EAUTH' || primaryErr.message?.includes('Authentication') || primaryErr.responseCode === 535;
      if (isAuthErr) {
        console.warn('[Email] Primary SMTP auth failed — permanently disabling primary transport');
        primaryTransport = null;
      }
      
      console.log('[Email] Triggering global fallback mechanism...');
      // Proceed to Gmail fallback immediately
    }
  } else {
    console.warn('[Email] Primary SMTP not configured or disabled — using fallback Gmail');
  }

  // ── Fallback Gmail ────────────────────────────────────────────────────────
  if (fallbackTransport) {
    try {
      // Override from address for Gmail fallback, but keep exact same template structure
      const fallbackFrom = process.env.FALLBACK_EMAIL || 'hello.shinerva@gmail.com';
      const gmailOptions = {
        ...mailOptions,
        from: fallbackFrom,
      };
      
      await fallbackTransport.sendMail(gmailOptions);
      console.log(`[Email] ✓ Sent via fallback Gmail (${fallbackFrom}) → ${to}`);
      return { success: true, transport: 'fallback Gmail', from: fallbackFrom };
    } catch (fallbackErr) {
      console.error(`[Email] Fallback Gmail also failed for ${to}: ${fallbackErr.message}`);
      throw new Error(`Gagal mengirim email. Silakan coba lagi atau hubungi support. (Gmail error: ${fallbackErr.message})`);
    }
  }

  // ── No transport available ────────────────────────────────────────────────
  throw new Error('Tidak ada konfigurasi email yang aktif. Pastikan SMTP atau Gmail sudah diset.');
}

// ─── Convenience Wrappers ─────────────────────────────────────────────────────

/**
 * Sends a magic link email to the given address.
 * Generates the token server-side, sends via best available transport.
 */
export async function sendMagicLinkEmail({ to, continueUrl }) {
  const link = await generateMagicLinkToken(to, continueUrl);
  const { subject, html } = buildMagicLinkEmail(link, to);
  return sendEmail({ to, subject, html });
}

/**
 * Sends an email verification link.
 * Note: Firebase Admin SDK cannot send verification emails directly.
 * This requires the user's ID token which is only available client-side.
 * Use the client SDK's sendEmailVerification() for now, or pass the ID token
 * to this server function if you prefer SMTP delivery.
 */
export async function sendVerificationEmail({ to, idToken: _idToken, continueUrl }) {
  // idToken param kept for signature compatibility — Firebase Admin generates the
  // verification link server-side without needing the client's ID token.
  if (!firebaseAdminAuth) {
    throw new Error('Firebase Admin not available for verification email');
  }
  try {
    // Generate verification link server-side using the user's ID token
    const link = await firebaseAdminAuth.generateEmailVerificationLink(to, {
      url: continueUrl || process.env.EMAIL_CONTINUE_URL || process.env.APP_URL || 'https://shinerva.id',
    });
    const { subject, html } = buildVerificationEmail(link, to);
    return sendEmail({ to, subject, html });
  } catch (err) {
    console.error(`[Email] Verification email failed for ${to}:`, err.message);
    throw new Error(`Gagal mengirim email verifikasi: ${err.message}`);
  }
}

/**
 * Sends a password reset email.
 */
export async function sendPasswordResetEmail({ to }) {
  if (!firebaseAdminAuth) {
    throw new Error('Firebase Admin not available for password reset');
  }
  try {
    const link = await firebaseAdminAuth.generatePasswordResetLink(to);
    const { subject, html } = buildPasswordResetEmail(link);
    return sendEmail({ to, subject, html });
  } catch (err) {
    console.error(`[Email] Password reset failed for ${to}:`, err.message);
    throw new Error(`Gagal mengirim email reset password: ${err.message}`);
  }
}

// ─── Health Check ────────────────────────────────────────────────────────────

/**
 * Returns email service health status for diagnostics.
 */
export async function getEmailHealth() {
  const checks = {};

  if (primaryTransport) {
    checks.primary = await probeTransport(primaryTransport, 'primary SMTP');
  } else {
    checks.primary = 'not_configured';
  }

  if (fallbackTransport) {
    checks.fallback = await probeTransport(fallbackTransport, 'fallback Gmail');
  } else {
    checks.fallback = 'not_configured';
  }

  checks.firebaseAdminAuth = !!firebaseAdminAuth;

  return checks;
}
